### PR TITLE
fix(builder): allow for none transaction receipt

### LINKED ISSUE #489: Debug tokio runtime panics
```
{
  "timestamp": "2023-11-01T18:41:21.332409Z",
  "level": "ERROR",
  "fields": {
    "message": "Builder server error: task 230 panicked"
  },
  "target": "rundler_builder::task"
}

```

This error has happened periodically and we would like to see the stack trace

### PR DESCRIPTION
**Pull request by alex-miao**
Closes #489

### CODE REVIEW

File: crates/builder/src/transaction_tracker.rs [hunk 1]
```diff
@@ -388,12 +388,16 @@ where
         }
     }
 
-    async fn get_mined_tx_gas_info(&self, tx_hash: H256) -> anyhow::Result<(U256, U256)> {
+    async fn get_mined_tx_gas_info(&self, tx_hash: H256) -> anyhow::Result<(U256, Option<U256>)> {
```
Comment (0xfourzerofour) [inline crates/builder/src/transaction_tracker.rs:391]: we might want to log this for our own research so that we can get to the bottom of what is happening with the nodes

**Review by 0xfourzerofour — APPROVED** [review]
