### PR TITLE
fix(reputation): do not increase ops seen on replacement

### LINKED ISSUE #498: [pool] Reputation for replacement operations
**Describe the feature**
When a UO is replaced in the mempool we should update the reputation tracker and reduce the `OPS_SEEN` count for each entity involved in the replaced op by 1.

### PR DESCRIPTION
**Pull request by alex-miao**
Closes #498

## Proposed Changes

  - Only update reputation if op is not a replacement

### CODE REVIEW

File: crates/pool/src/mempool/uo_pool.rs [hunk 1]
```diff
@@ -457,11 +457,13 @@ where
 
         // Update reputation
         pool_op.entities().unique().for_each(|e| {
```
Comment (0xfourzerofour) [inline crates/pool/src/mempool/uo_pool.rs:459]: Maybe put the replacement check outside the `for_each` so we can skip going through it all together on replacements

**Review by 0xfourzerofour — COMMENTED** [review]
I think this    should be sd

**Review by 0xfourzerofour — APPROVED** [review]
LGTM
