### PR TITLE
feat(rpc): add state overrides to estimate gas, fix error msg

### LINKED ISSUE #525: [rpc] Add state overrides to `eth_estimateUserOperationGas`
**Describe the feature**
See https://github.com/eth-infinitism/account-abstraction/pull/381

### LINKED ISSUE #530: [rpc] Improve error format for reverts during `eth_estimateUserOperationGas`
**Describe the feature**
We currently return a string with the hex bytes from the user's revert: https://github.com/alchemyplatform/rundler/blob/53438410c30539685ddc0fd1538dd7201c040f14/crates/sim/src/estimation/estimation.rs#L78

This relies on the user to parse our error message string, which is very brittle. We should return the hex has part of the data field of the json RPC response.

### PR DESCRIPTION
**Pull request by dancoombs**
Closes #525
Closes #530

## Proposed Changes

  - Add state overrides to `eth_estimateUserOperationGas`
  - Move revert bytes to `revert_bytes` in the data field of the `eth_estimateUserOperationGas` error response
 
## TODO

- [x] Test state overrides using a USDC paymaster
- [x] Test revert bytes using a contract that returns a non-string error

### CODE REVIEW

**Comment by dancoombs** [comment]
Tested revert bytes by calling https://github.com/eth-infinitism/account-abstraction/blob/187613b0172c3a21cf3496e12cdfa24af04fb510/contracts/core/EntryPoint.sol#L356 on the entry point, the revert error is correctly formatted.

```
body: '{"jsonrpc":"2.0","error":{"code":-32521,"message":"execution reverted","data":{"revertData":"0x6ca7b8060000000000000000000000007e7df6dc443993a2c6fb67edcfd41522a6ffc49a"}},"id":43}',
```

File: crates/sim/src/estimation/estimation.rs [hunk 1]
```diff
@@ -194,14 +184,18 @@ impl<P: Provider, E: EntryPoint> GasEstimatorImpl<P, E> {
...
         let simulation_gas = U256::from(self.settings.max_simulate_handle_ops_gas);
+        let gas_fee = U256::from(self.settings.validation_estimation_gas_fee);
 
-        // Make one attempt at max gas, but zero fees, to see if success is possible.
+        // Make one attempt at max gas, to see if success is possible.
         // Capture the gas usage of this attempt and use as the initial guess in the binary search
+
         let initial_op = UserOperation {
             verification_gas_limit: simulation_gas,
+            max_fee_per_gas: gas_fee / (simulation_gas + op.pre_verification_gas),
```
Comment (0xfourzerofour) [inline crates/sim/src/estimation/estimation.rs:198]: Nit: whenever doing small math functions we should use the checked version or saturated version to be safe

**Review by 0xfourzerofour — APPROVED** [review]
Looks good, just a nit math comment

**Review by 0xfourzerofour — APPROVED** [review]

File: crates/sim/src/estimation/estimation.rs [hunk 2]
```diff
@@ -243,14 +244,26 @@ impl<P: Provider, E: EntryPoint> GasEstimatorImpl<P, E> {
...
                     simulation_gas,
-                    &spoof::state(),
+                    state_override,
                 )
                 .await?
                 .err();
-            Result::<_, anyhow::Error>::Ok(error_message)
+
+            if let Some(error_message) = error_message {
+                if error_message.contains("OOG") || error_message.contains("AA40") {
```
Comment (alex-miao) [inline crates/sim/src/estimation/estimation.rs:253]: Just to clarify the OOG case is meant to capture `AA13`, `AA23`, and `AA33`?

File: crates/sim/src/estimation/estimation.rs [hunk 3]
```diff
@@ -243,14 +244,26 @@ impl<P: Provider, E: EntryPoint> GasEstimatorImpl<P, E> {
...
+                    // This error occurs when out of gas, return true.
```
Comment (alex-miao) [inline crates/sim/src/estimation/estimation.rs:254]: nit: did you mean "return false"

File: crates/sim/src/estimation/estimation.rs (hunk 2 above)
Comment (dancoombs) [reply crates/sim/src/estimation/estimation.rs:253]: Yeah, I'll update this to be explicit

Comment (alex-miao) [reply crates/sim/src/estimation/estimation.rs]: Do we also need to check `AA41` here?

**Review by alex-miao — APPROVED** [review]

**Review by alex-miao — APPROVED** [review]
