### PR TITLE
feat(compliance): fixes for spec tests

### LINKED ISSUE #531: STO-033
Update tracer to differentiate between read and write storage access

### PR DESCRIPTION
**Pull request by 0xfourzerofour**
Closes #531 

## Proposed Changes

  - Seperated read and write access from tracer
  - change tracer parsing logic to follow similar implementation as the reference bundler https://github.com/eth-infinitism/bundler/blob/ba78f2067e33df399bb7d34a9d1f972834d23c80/packages/validation-manager/src/TracerResultParser.ts#L315
  - Changed error codes to work with spec tests
  - Update error message to work with spec tests

### CODE REVIEW

File: crates/rpc/src/eth/error.rs [hunk 1]
```diff
@@ -251,14 +251,15 @@ impl From<EthRpcError> for ErrorObjectOwned {
...
+            | EthRpcError::StakeTooLow(_)
+            | EthRpcError::SimulationFailed(_)
             | EthRpcError::InvalidStorageAccess(_, _, _) => rpc_err(OPCODE_VIOLATION_CODE, msg),
             EthRpcError::OutOfTimeRange(data) => {
                 rpc_err_with_data(OUT_OF_TIME_RANGE_CODE, msg, data)
             }
             EthRpcError::ThrottledOrBanned(data) => {
                 rpc_err_with_data(THROTTLED_OR_BANNED_CODE, msg, data)
             }
-            EthRpcError::StakeTooLow(data) => rpc_err_with_data(STAKE_TOO_LOW_CODE, msg, data),
```
Comment (alex-miao) [inline crates/rpc/src/eth/error.rs:261]: Why don't we need this anymore

Comment (0xfourzerofour) [reply crates/rpc/src/eth/error.rs:261]: it was just added up a few lines to use opcode violation code. Techically it is correct but the spec tests just opcode violations for most errors so we are just complying with the 4337 team

File: crates/sim/src/simulation/simulation.rs [hunk 2]
```diff
@@ -703,9 +696,9 @@ struct ValidationContext {
     entity_infos: EntityInfos,
     tracer_out: SimulationTracerOutput,
     entry_point_out: ValidationOutput,
-    is_unstaked_wallet_creation: bool,
```
Comment (alex-miao) [inline crates/sim/src/simulation/simulation.rs:706]: Nice, good to see that we can derive this from what we already have and get rid of this redundancy. I've been thinking that it might be possible to consolidate `entity_infos` and `entities_needing_stake` but haven't looked into it too much.

File: crates/sim/src/simulation/simulation.rs [hunk 3]
```diff
@@ -804,48 +823,81 @@ fn entity_type_needs_stake(
...
+            if initcode_length > 2
+                // special case: account.validateUserOp is allowed to use assoc storage if factory is staked.
+                // [STO-022], [STO-021]
+                && !(entity.address.eq(&sender)
+                    && entity_infos
+                        .factory
+                        .expect("Factory needs to be present and staked")
+                        .is_staked)
+            {
+                required_stake_slot = Some(slot);
```
Comment (alex-miao) [inline crates/sim/src/simulation/simulation.rs:885]: nit: we could potentially break out of the loop here, unless you prefer returning `Banned` before `NeedsStake`

File: crates/sim/tracer/src/validationTracer.ts [hunk 4]
```diff
@@ -233,13 +236,19 @@ type StringSet = Record<string, boolean | undefined>;
...
     step(log, db): void {
       if (!entryPointAddress) {
         entryPointAddress = toHex(log.contract.getAddress());
       }
-      if (log.getGas() < log.getCost()) {
+
+      const opcode = log.op.toString();
+
+      if (log.getGas() < log.getCost() || (
+        opcode === 'SSTORE' && log.getGas() < 2300
```
Comment (alex-miao) [inline crates/sim/tracer/src/validationTracer.ts:250]: nit: can we make 2300 a constant

File: crates/sim/tracer/src/validationTracer.ts [hunk 5]
```diff
@@ -312,19 +319,33 @@ type StringSet = Record<string, boolean | undefined>;
...
           // The entry point can access whatever it wants, but otherwise track
           // access for this phase so we can check validity later.
-          computeIfAbsent(
-            currentPhase.storageAccesses,
-            addressHex,
-            (): StringSet => ({})
-          )[slotHex] = true;
+          if (opcode == "SLOAD") {
+            // Read access
+            if (access.reads[slotHex] == null && access.writes[slotHex] == null) {
```
[the remark this answers is not in the document]
Comment (0xfourzerofour) [reply crates/sim/tracer/src/validationTracer.ts:341]:
```
          // read slot values before this UserOp was created
          // (so saving it if it was written before the first read)

```

This is the explanation from ref bundler

File: crates/sim/src/simulation/simulation.rs [hunk 6]
```diff
@@ -804,48 +823,81 @@ fn entity_type_needs_stake(
...
+        let is_sender_associated = slots_by_address.is_associated_slot(sender, *slot);
+        // [STO-032]
+        let is_entity_associated = slots_by_address.is_associated_slot(entity.address, *slot);
+        // [STO-031]
+        let is_same_address = address.eq(&entity.address);
+        // [STO-033]
+        let is_read_permission = !access_info.writes.contains_key(slot);
+
+        if is_sender_associated {
+            if initcode_length > 2
```
Comment (alex-miao) [inline crates/sim/src/simulation/simulation.rs:876]: Is this because an "empty" initcode is `0x`

**Review by alex-miao — APPROVED** [review]
🚀

File: crates/sim/src/simulation/simulation.rs (hunk 6 above)
Comment (0xfourzerofour) [reply crates/sim/src/simulation/simulation.rs:876]: yeh exactly

File: crates/sim/src/simulation/simulation.rs (hunk 3 above)
Comment (0xfourzerofour) [reply crates/sim/src/simulation/simulation.rs:885]: I think I would prefer to just keep it as is for readability

File: crates/rpc/src/eth/error.rs [hunk 7]
```diff
@@ -35,7 +35,7 @@ const PAYMASTER_VALIDATION_REJECTED_CODE: i32 = -32501;
 const OPCODE_VIOLATION_CODE: i32 = -32502;
 const OUT_OF_TIME_RANGE_CODE: i32 = -32503;
 const THROTTLED_OR_BANNED_CODE: i32 = -32504;
-const STAKE_TOO_LOW_CODE: i32 = -32505;
+const _STAKE_TOO_LOW_CODE: i32 = -32505;
```
Comment (dancoombs) [inline crates/rpc/src/eth/error.rs:38]: Interesting that this is defined in the spec but never used by the spec tests

File: crates/rpc/src/types.rs [hunk 8]
```diff
@@ -169,7 +170,7 @@ pub struct RpcReputation {
     /// Number of operations included in this interval
     pub ops_included: U256,
     /// Reputation status
-    pub status: ReputationStatus,
+    pub status: Option<ReputationStatus>,
```
Comment (dancoombs) [inline crates/rpc/src/types.rs:173]: Is there a use case where this is actually optional in an API? Or is there a request type that omits and a response type that includes? We may want to represent that as 2 separate types to have more strict API format.

File: crates/rpc/src/types.rs [hunk 9]
```diff
@@ -178,7 +179,7 @@ impl From<RpcReputation> for Reputation {
             address: rpc_reputation.address,
             ops_seen: rpc_reputation.ops_seen.as_u64(),
             ops_included: rpc_reputation.ops_included.as_u64(),
-            status: rpc_reputation.status,
+            status: rpc_reputation.status.unwrap_or(ReputationStatus::Ok),
```
Comment (dancoombs) [inline crates/rpc/src/types.rs:182]: Can we remove `status` from our internal `Reputation` object? Just calculate it where we need it based on `ops_seen` and `ops_included`?

File: crates/sim/src/simulation/tracer.rs [hunk 10]
```diff
@@ -71,9 +71,9 @@ pub(crate) struct Phase {
 
 #[derive(Clone, Debug, Deserialize, Serialize)]
 #[serde(rename_all = "camelCase")]
-pub(crate) struct StorageAccess {
-    pub(crate) address: Address,
-    pub(crate) slots: Vec<U256>,
+pub(crate) struct AccessInfo {
+    pub(crate) reads: HashMap<U256, String>,
+    pub(crate) writes: HashMap<U256, u32>,
```
Comment (dancoombs) [inline crates/sim/src/simulation/tracer.rs:76]: Can you add comments to what the values in these hashmaps represent? Hard to tell from the code

File: crates/sim/tracer/src/validationTracer.ts [hunk 11]
```diff
@@ -233,13 +237,19 @@ type StringSet = Record<string, boolean | undefined>;
...
     step(log, db): void {
       if (!entryPointAddress) {
         entryPointAddress = toHex(log.contract.getAddress());
       }
-      if (log.getGas() < log.getCost()) {
+
+      const opcode = log.op.toString();
+
+      if (log.getGas() < log.getCost() || (
+        opcode === 'SSTORE' && log.getGas() < SSTORE_REQUIRED_GAS
```
Comment (dancoombs) [inline crates/sim/tracer/src/validationTracer.ts:251]: Was this just something we missed before? How come the existing check doesn't catch this?

File: crates/rpc/src/types.rs (hunk 8 above)
Comment (0xfourzerofour) [reply crates/rpc/src/types.rs:173]: This is more for the fact that the json RPC library we use doe not allow us to omit the field if it is defined like this, but I think it would make more sense to seperate the rpc type with a Reputation input and Reputation Output so that we can calculate on the fly brought up below

File: crates/sim/tracer/src/validationTracer.ts (hunk 11 above)
Comment (0xfourzerofour) [reply crates/sim/tracer/src/validationTracer.ts:251]: Its just something we missed. It is a weird case where even if SSTORE takes less than 2300 gas we still need to  have at least that or it will be an OOG error

File: crates/sim/tracer/src/validationTracer.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (dancoombs) [reply crates/sim/tracer/src/validationTracer.ts:342]: Can we add a similar comment to our code here?

File: crates/sim/src/simulation/simulation.rs [hunk 12]
```diff
@@ -804,48 +823,81 @@ fn entity_type_needs_stake(
...
+                // special case: account.validateUserOp is allowed to use assoc storage if factory is staked.
+                // [STO-022], [STO-021]
+                && !(entity.address.eq(&sender)
+                    && entity_infos
+                        .factory
+                        .expect("Factory needs to be present and staked")
+                        .is_staked)
```
Comment (dancoombs) [inline crates/sim/src/simulation/simulation.rs:883]: This logic looks different than the logic we removed 

`accessed_address == entry_point_address || !is_unstaked_wallet_creation`

what is the reason for the difference?

> special case: account.validateUserOp is allowed to use assoc storage if factory is staked.

This isn't how I read STO-21/STO-22, it seems like this should apply to the paymaster and factory as well? Is this a difference in the spec vs how the reference is implemented?

Comment (0xfourzerofour) [reply crates/sim/src/simulation/simulation.rs:883]: Yeh our existing implementation was a little hard to understand but this is how it should be implented. STO-022 is just regarding the factory and whether it has an init code

File: crates/rpc/src/types.rs (hunk 9 above)
Comment (0xfourzerofour) [reply crates/rpc/src/types.rs:182]: This has some pretty annoying consequences, because the status computation requires internal config from the Reputation manager. We could add to the proto so that we can read the status over the wire but that does not seem ideal

File: crates/sim/src/simulation/simulation.rs (hunk 12 above)
Comment (dancoombs) [reply crates/sim/src/simulation/simulation.rs:883]: It seems like the code and the description in the ERC don't match though. Why doesn't this apply to the paymaster?

File: crates/rpc/src/types.rs (hunk 8 above)
Comment (dancoombs) [reply crates/rpc/src/types.rs:173]: Yeah, it would be great to clean up the types here, at least on on the RPC side.

File: crates/rpc/src/types.rs (hunk 9 above)
Comment (dancoombs) [reply crates/rpc/src/types.rs:182]: Got it, just seems odd to me that the `status` could say `OK` but the `ops_seen`/`ops_included` would indicate otherwise. Any thoughts on how to clean that up?

Comment (0xfourzerofour) [reply crates/rpc/src/types.rs:182]: I am ok adding GetReputationStatus to the op_pool in the proto. I have been playing around with the code and even though the request is over the wire  if running in distributed mode I think it is cleaner than other options

File: crates/sim/src/simulation/simulation.rs (hunk 12 above)
Comment (0xfourzerofour) [reply crates/sim/src/simulation/simulation.rs:883]: It matches in my head

Both rules are asking if the account entity (sender) can access the associated storage slots of the contract itself or the associate slot of the sender in another contract.

[STO-021]  The account already exists
- This is checked in the tracer and returned by the AccessedUndeployedContract error

[STO-022]  There is an `initCode` and the `factory` contract is staked
- Checked here on line 879

This is just how I have thought about the rules over the past few days. Do you think it means something else?

Comment (dancoombs) [reply crates/sim/src/simulation/simulation.rs:883]: I don't see anything that limits this rule to apply only to the account entity. It reads to me like both the paymaster/factory need to be limited as well.

If the factory isn't staked, then no entity can read associated storage during deployment

Comment (0xfourzerofour) [reply crates/sim/src/simulation/simulation.rs:883]: I think we should ask the 4337 team because I dont think it is clear as the wording makes it ambiguous

https://github.com/eth-infinitism/account-abstraction/blob/develop/eip/EIPS/eip-aa-rules.md?plain=1#L209

Comment (0xfourzerofour) [reply crates/sim/src/simulation/simulation.rs:883]: https://github.com/eth-infinitism/bundler/blob/ba78f2067e33df399bb7d34a9d1f972834d23c80/packages/validation-manager/src/TracerResultParser.ts#L322

Comment (dancoombs) [reply crates/sim/src/simulation/simulation.rs:883]: https://github.com/eth-infinitism/bundler/commit/32725c2cc028c32ed7f12aea0e1eb3438d9d8e79

You are correct! The wording can probably be improved on the erc-aa-rules

**Review by dancoombs — APPROVED** [review]
🚢 

Great work on this, tough to get all these details ironed out!
